name: Build Forge Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用较旧的 Ubuntu 版本以确保兼容性

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用较旧的 checkout 版本
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v2  # 使用较旧的 setup-java 版本
      with:
        java-version: '8'
        distribution: 'zulu'  # 使用 Zulu JDK 8，兼容性更好

    - name: Validate Gradle Wrapper
      run: |
        chmod +x gradlew
        # 先下载 Gradle 包装器
        wget https://github.com/gradle/gradle/releases/download/v4.4.1/gradle-4.4.1-bin.zip -P /tmp/
        unzip /tmp/gradle-4.4.1-bin.zip -d /tmp/
        cp /tmp/gradle-4.4.1/lib/gradle-wrapper.jar gradle/wrapper/
        ./gradlew --version

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace --info

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3  # 使用较旧的 upload-artifact 版本
      with:
        name: BuildOutput
        path: build/libs/
